services:
  - type: web
    name: e-commerce-symfony
    env: docker
    repo: https://github.com/novembre-staff/e-commerce-Symfony-6
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: LOOKUP_PROVIDER
        value: cascade
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: e-commerce-db
          property: connectionString
    healthCheckPath: /

databases:
  - name: e-commerce-db
    databaseName: ecommerce
    user: ecommerce
